### ISSUE TITLE
run with error

### ISSUE THREAD

**Issue by asukasukasukasuka** [reorx/xiami_exporter#1]
after running 'python -m xiami_exporter.cli create-songs-db'

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/xiami_exporter/xiami_exporter/cli.py", line 258, in <module>
    cli()
  File "/opt/xiami_exporter/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/xiami_exporter/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/xiami_exporter/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/xiami_exporter/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/xiami_exporter/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/xiami_exporter/xiami_exporter/cli.py", line 127, in create_songs_db
    prepare_db()
  File "/opt/xiami_exporter/xiami_exporter/cli.py", line 50, in prepare_db
    db.create_tables(all_models)
  File "/opt/xiami_exporter/lib/python3.6/site-packages/peewee.py", line 3317, in create_tables
    model.create_table(**options)
  File "/opt/xiami_exporter/lib/python3.6/site-packages/peewee.py", line 6648, in create_table
    cls._schema.create_all(safe, **options)
  File "/opt/xiami_exporter/lib/python3.6/site-packages/peewee.py", line 5775, in create_all
    self.create_table(safe, **table_options)
  File "/opt/xiami_exporter/lib/python3.6/site-packages/peewee.py", line 5630, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/opt/xiami_exporter/lib/python3.6/site-packages/peewee.py", line 3142, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/opt/xiami_exporter/lib/python3.6/site-packages/peewee.py", line 3127, in execute_sql
    cursor = self.cursor(commit)
  File "/opt/xiami_exporter/lib/python3.6/site-packages/peewee.py", line 3111, in cursor
    self.connect()
  File "/opt/xiami_exporter/lib/python3.6/site-packages/peewee.py", line 3065, in connect
    self._state.set_connection(self._connect())
  File "/opt/xiami_exporter/lib/python3.6/site-packages/peewee.py", line 3402, in _connect
    isolation_level=None, **self.connect_params)
TypeError: argument 1 must be str, not PosixPath

```

**Comment by reorx** [comment]
我的 macOS 和 Python 3.7 没有复现，但从错误看应该是 pathlib 的兼容问题，这个提交应该可以修复 7aabcef

**Comment by reorx** [comment]
closed for no further response and no reproduction.
